# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hazzik's blog
tagline:          ''
description:      ''
url:              http://blog.hazzik.ru
timezone:         'NZS-12:00'
tag_page_layout: tag_page
tag_page_dir: tag

author:
  name:           'Alexander Zaytsev'
  url:            http://blog.hazzik.ru

paginate:         5

github:
  source:    'http://github.com/hazzik/blog.hazzik.ru/edit/gh-pages/'

ya_metrika_id:    13173247

gems:
  - jekyll-redirect-from
