# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        pretty

# Setup
title:            Hazzik's blog
tagline:          ''
description:      ''
url:              http://blog.hazzik.ru
timezone:         'Pacific/Auckland'

author:
  name:           'Alexander Zaytsev'
  url:            http://blog.hazzik.ru

paginate:         5

github:
  source:    'http://github.com/hazzik/blog.hazzik.ru/edit/gh-pages/'

gems:
  - jekyll-redirect-from
