source 'https://rubygems.org'
gem 'octopress'
gem 'octopress-deploy', :git => 'https://github.com/hazzik/octopress-deploy.git'
gem 'rouge'
gem 'jekyll-redirect-from'
gem 'jekyll-tagging', :git => 'https://github.com/hazzik/jekyll-tagging.git'
