source 'https://rubygems.org'
gem 'octopress', :git => 'https://github.com/hazzik/octopress.git'
gem 'octopress-deploy'
gem 'rouge'
gem 'jekyll-redirect-from'
gem 'jekyll-tagging', :git => 'https://github.com/hazzik/jekyll-tagging.git'
